{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ article.title }}{% endblock %}
{% block description %}{{ article.description }}{% endblock %}
{% block content %}
<div class="article_container">
<div class="article_info">
<h3>{{ article.title }}</h3>
<p>{{ article.description }}</p>
</div>
{{ article.content }}
</div>
{% if article.is_likeable == True %}
<div class="facebook_control">
<div class="fb-like" data-href="{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</div>
{% endif %}
{% endblock %}
