<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}title of site{% endblock %}</title>
        <meta charset="UTF-8" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="/media/layout.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic,100,100italic,300,300italic,500,500italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>    
<link href='http://fonts.googleapis.com/css?family=Exo:200,400,600,800,600italic,200italic,400italic,800italic' rel='stylesheet' type='text/css'>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53656906-1', 'auto');
  ga('send', 'pageview');

</script>
</head>
    <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


    {% block content %}{% endblock %}
    </body>
</html>
