<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}title of site{% endblock %}</title>
        <meta charset="UTF-8" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="/media/layout.css">
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:100,400,800,900,400italic,100italic,800italic' rel='stylesheet' type='text/css'>
    </head>
    <body>
    {% block content %}{% endblock %}
    </body>
</html>
