<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}title of site{% endblock %}</title>
        <meta charset="UTF-8" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="/media/layout.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic,100,100italic,300,300italic,500,500italic,900,900italic' rel='stylesheet' type='text/css'>
    </head>
    <body>
    {% block content %}{% endblock %}
    </body>
</html>
