{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ gallery.title }}{% endblock %}
{% block description %}{{ gallery.description }}{% endblock %}
{% block content %}
<div class="gallery_container">
<div class="gallery_info">
<h3>{{ gallery.title }}</h3>
<p>{{ gallery.description }}</p>
</div>

{% for galimage in gallery.galimages.all %}
<div class="preview_image_container">
<div style="position: relative">
<a class="preview_image_link" href="../detail/{{ galimage.id }}/">
<img class="preview_image" src="{{ galimage.base_file.url }}.thumb.jpg"/>
</a>
<p class="preview_image_name">{{ galimage.name }}</p>
</div>
</div>
{% endfor %}
</div>
{% if gallery.is_likeable == True %}
<div class="facebook_control">
<div class="fb-like" data-href="{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</div>
{% endif %}
{% endblock %}
