{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ gallery.title }}{% endblock %}
{% block description %}{{ gallery.description }}{% endblock %}
{% block content %}
<div class="gallery_control_left gallery_control">
    <a class="last_image_control" href="">last</a>
</div>
<div class="gallery_control_right gallery_control">
    <a class="next_image_control" href="">next</a>
</div>
<div class="gallery_control_center gallery_control">
    <a class="back_to_site_control" href="../../">back to site</a>
</div>
<div class="image_info gallery_control">
    <p class="image_name">{{ image.name }}</p>
    <p class="image_description">{{ image.description }}</p>
    <p class="image_take_date">{{ image.make_date }}</p>
    <p class="image_place">{{ image.place }}</p>
</div>
<img class="gallery_big_image" src="{{ image.base_file.url }}" alt="{{ image.name }}"/>

{% endblock %}
