{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ gallery.title }}{% endblock %}
{% block description %}{{ gallery.description }}{% endblock %}
{% block content %}

{% for galimage in gallery.galimages.all %}
<div class="preview_image_container">
<div style="position: relative">
<a class="preview_image_link" href="../detail/{{ galimage.id }}/">
<img class="preview_image" src="{{ galimage.base_file.url }}.thumb.jpg"/>
</a>
<p class="preview_image_name">{{ galimage.name }}</p>
</div>
</div>
{% endfor %}

{% endblock %}
