{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ gallery.title }}{% endblock %}
{% block description %}{{ gallery.description }}{% endblock %}
{% block content %}
<img class="gallery_big_image" src="{{ image.base_file.url }}" alt="{{ image.name }}">
{% if not last == 'none' %}
<div class="gallery_control_left gallery_control fade-out">
    <a class="last_image_control" href="./../{{ last }}">last</a>
</div>
{% endif %}
{% if not next == 'none' %}
<div class="gallery_control_right gallery_control fade-out">
    <a class="next_image_control" href="./../{{ next }}">next</a>
</div>
{% endif %}
<div class="gallery_control_center gallery_control fade-out">
    <a class="back_to_site_control" href="../../overview/">exit</a>
</div>
<div class="image_info gallery_control fade-out">
    <div class="image_info_left">
    <p class="image_name">{{ image.name }}</p>
    <hr/>
    <p class="image_take_date">{{ exif.Exif_Photo_DateTimeOriginal }}</p>
    <p class="image_place">{{ image.place }}</p>
    {% if not latstr == "unknown" %}
    <p class="image_place">Länge: {{ latstr }} {% if latref == "North" %}Nord{% else %}S&uumld{% endif %}</p>
    <p class="image_place">Breite: {{ lonstr }} {% if lonref == "East" %}Ost{% else %}West{% endif %}</p>
    {% if not altstr == "unknown" %}
    <p class="image_place">Höhe: {{ altstr }}</p>
    {% endif %}

    <p class="image_place">
    <img class="map" src="http://maps.google.com/maps/api/staticmap?center={{ googlelat }},{{ googlelon }}&zoom=14&size=300x200&maptype=roadmap&markers=color:blue|label:test|{{ googlelat }},{{ googlelon }}&sensor=false"></img> 
    </p>
    {% endif %}
        <hr/>
    <p class="image_description">{{ image.description }}</p>
    </div>
    <div class="image_info_right">
    

    <p class="image_info_meta">Kamera:
                {% if exif.Exif_Image_Make %}{{ exif.Exif_Image_Make }}{% endif %} 
                {% if exif.Exif_Image_Model %}  - {{ exif.Exif_Image_Model }}{% endif %}</p>
    {% if exif.Exif_NikonLd3_LensIDNumber %}
    <p class="image_info_meta">Objektiv: {{ exif.Exif_NikonLd3_LensIDNumber }}</p>
    {% endif %}
    {% if exif.Exif_Photo_Flash %}
    <p class="image_info_meta">Blitz: {{ exif.Exif_Photo_Flash }}</p>
    {% endif %}
    {% if exif.Exif_Nikon3_Focus %}
    <p class="image_info_meta">Fokusmodus: {{ exif.Exif_Nikon3_Focus }}</p>
    {% endif %}
    {% if exif.Exif_NikonLd3_FocusDistance %}
    <p class="image_info_meta">Fokusentfernung: {{ exif.Exif_NikonLd3_FocusDistance }}</p>
    {% endif %}
    {% if exif.Exif_NikonLd3_FocalLength %}
    <p class="image_info_meta">Brennweite: {{ exif.Exif_NikonLd3_FocalLength }}</p>
    {% endif %}
    {% if exif.Exif_Photo_FocalLengthIn35mmFilm %}
    <p class="image_info_meta">Brennweite (Kleinbildäquivalent): {{ exif.Exif_Photo_FocalLengthIn35mmFilm }}</p>
    {% endif %}
    {% if exif.Exif_Photo_FNumber %}
    <p class="image_info_meta">Blende: {{ exif.Exif_Photo_FNumber }}</p>
    {% endif %}
    {% if exif.Exif_Photo_ExposureTime %}
    <p class="image_info_meta">Belichtungszeit: {{ exif.Exif_Photo_ExposureTime }}</p>
    {% endif %}
    {% if exif.Exif_Photo_ISOSpeedRatings %}
    <p class="image_info_meta">ISO: {{ exif.Exif_Photo_ISOSpeedRatings }}</p>
    {% endif %}
    {% if exif.Exif_Image_Copyright %}
    <p class="image_info_meta">Copyright: {{ exif.Exif_Image_Copyright|safe }}</p>
    {% endif %}
    {% if exif.Exif_Image_Artist %}
    <p class="image_info_meta">Fotograf: {{ exif.Exif_Image_Artist }}</p>
    {% endif %}
    </div>
{% if image.is_likeable == True %}
<div class="fb-like" data-href="{{ request.get_full_path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
{% endif %}
    <div class="image_info_clear"/>
</div>
</img>
{% endblock %}
