{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ gallery.title }}{% endblock %}
{% block description %}{{ gallery.description }}{% endblock %}
{% block content %}
<h1>{{ gallery.title }}</h1>
<p>{{ gallery.description}}</p>

{% for galimage in gallery.galimages.all %}
 
<a class="preview_link" href="../detail/{{ galimage.id }}/">
<img class="preview_image" style="float: left;" src="{{ galimage.base_file.url }}.thumb.jpg"/>
</a>

{% endfor %}



{% endblock %}
