{% extends "core/base.phtml" %}
{% load staticfiles %}
{% block title %}{{ site.title }}{% endblock %}
{% block description %}{{ site.description }}{% endblock %}
{% block content %}

<div class="site_menu">
{% for s in sites %}
<a class="site_menu_link" href="../{{ s.id }}">{{ s.title }}</a>
{% endfor %}
</div>

<div style="margin-top: 2em; padding-top:2em; margin-right:10%;margin-left:10%; background: url(/media/siteheader.jpg) green; height: 300px;" class"site_header_container">
<h1 class="site_title">{{ site.title }}</h1>
<h2 class="site_subtitle">{{ site.subtitle }}</h2>
<p class="site_description">{{ site.description }}</p>
</div>

<div class="site_articles">
{% for article in articles %}
<h4>< a class="site_article_link" href="./article/{{ article.id }}/detail>"{{ article.title }}</a></h4>
<p>{{ article.description }}</p>
<p class="site_article_content">{{ article.content|truncatewords:"150" }}</p>
<hr/>
{% endfor %}
</div>
<div class="site_galleries">
{% for gallery in galleries %}
<h4><a class="site_gallery_link" href="./gallery/{{ gallery.id }}/overview">{{ gallery.title }}</a></h4>
<p>{{ gallery.description }}</p>
{% for image in gallery.galimages.all %}
<div class="site_gallery_preview">
<img class="site_gallery_preview_image" src="{{ image.base_file.url }}.thumb.jpg"/>
</div>




{% endfor %}
<hr/>
{% endfor %}
</div>
{% endblock %}
